# Generated by Django 3.2 on 2023-09-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopaap', '0004_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='shopaap.Product'),
        ),
    ]
